UPLOAD_DATA = 'upload-data'
DATA_TABLE = 'data-table'
RESULTS_CONTAINER = 'results-container'
SUBMIT_BUTTON_CONTAINER = 'submit-button-container'

PROBLEMS_DROPDOWN = 'problem-dropdown-selection'
TARGET_DROPDOWN = 'target-dropdown-selection'
MODELS_DROPDOWN = 'model-dropdown-selection'
FEATURE_DROPDOWN = 'feature-dropdown-selection'
MANUEL_FEATURE_DROPDOWN = 'manuel-feature-selection'

SELECT_PROBLEM_CONTAINER = 'select-problem-container'
SELECT_TARGET_CONTAINER = 'select-target-container'
SELECT_MODEL_CONTAINER = 'select-model-container'
SELECT_FEATURE_CONTAINER = 'select-feature-container'
SELECT_MANUEL_FEATURE_CONTAINER = 'select-manual-feature-container'